trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  BuildConfiguration: 'Release'
  UseSemanticRelease: 'true'

resources:
  repositories:
    - repository: templates
      type: git
      name: ErikLieben.FA/build-templates
    - repository: self
      type: github
      name: eriklieben/ErikLieben.FA.Results
      endpoint: github.com_eriklieben

extends:
    template: NuGet/main_template.yaml@templates
    parameters:
      repositoryName: 'eriklieben/ErikLieben.FA.Results'
      solutionPath: 'ErikLieben.FA.Results.sln'
      sonarCloudProjectKey: 'eriklieben_ErikLieben.FA.Results'
      buildConfiguration: '$(BuildConfiguration)'
      useSemanticRelease: true
      packageProjects:
        - displayName: 'library'
          path: 'src/ErikLieben.FA.Results/ErikLieben.FA.Results.csproj'
        - displayName: 'library.validations'
          path: 'src/ErikLieben.FA.Results.Validations/ErikLieben.FA.Results.Validations.csproj'


